### ISSUE TITLE
发张图片

### ISSUE THREAD

**Issue by fuyongfan** [fuyongfan/lianxi1#2]
![qq 20160526215106](https://cloud.githubusercontent.com/assets/17957375/15576764/0129faf2-238c-11e6-8a2a-f6ebf1976df0.png)

**Comment by tangbing1993** [comment]
asaadad
![head](https://cloud.githubusercontent.com/assets/17987181/15576803/38ead84e-238c-11e6-9498-5f7039f86b73.png)

**Comment by tangbing1993** [comment]
hello

**Comment by tangbing1993** [comment]
hello
